<?xml version="1.0" encoding="utf-8"?>
<report
	progress="">
	<activity
		result="Failed"
		duration="29.24s"
		durationms="29237"
		type="root"
		rid="4480db3077bf22c"
		totalerrorcount="1"
		totalwarningcount="0"
		totalsuccesstestcasecount="0"
		totalfailedtestcasecount="0"
		totalblockedtestcasecount="0"
		childsuccesscount="0"
		childfailedcount="0"
		childblockedcount="0"
		totalsuccesscount="0"
		totalfailedcount="0"
		totalblockedcount="0"
		totalmaintenancemodecount="0"
		user="Fahad Shah"
		rxversion="8.0.0.0"
		host="HUAWEI LUA-U22 (Unknown)
WLAN - 192.168.3.11"
		osversion="-"
		runtimeversion="-"
		procarch="-"
		oslanguage="-"
		dtnlanguage="-"
		screenresolution="-"
		timestamp="2/19/2018 4:56:30 PM"
		timestampiso="2018-02-19T11:56:30"
		endtime="2/19/2018 4:57:00 PM"
		timeoutfactor="1"
		module="TPOSMApplication">
		<detail>
			TPOSMApplication
		</detail>
		<varbindings>
		</varbindings>
		<item
			timeRelativeToTestSuiteStartTime="00:29.221"
			timeRelativeToTestModuleStartTime="00:29.221"
			timeWallClock="16:57:00"
			time="00:29.221"
			level="Error"
			category="Module">
			<message>
				The test run has been aborted by the user.
			</message>
			<metainfo
				loglvl="Error">
			</metainfo>
		</item>
	</activity>
</report>
